server {
    listen 80;
    server_name localhost;

    # Mengarahkan semua request UI ke container Vite
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Support WebSocket for Vite HMR
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Mengarahkan semua request yang berawalan /api ke container Golang
    location /api/ {
        # Tanda '/' di akhir http://backend:8080/ sangat penting
        # agar kata '/api' dihilangkan saat diteruskan ke Golang
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}